### ISSUE TITLE
Adding the C code for this seesion

### ISSUE THREAD

**Issue by neilwang0913** [PeterZhang17/HelloWorld#1]
// Simple C program to display "Hello World"  
// Header file for input output functions
#include <stdio.h>  
// main function -// where the execution of program begin

Refer to : https://www.geeksforgeeks.org/c-hello-world-program/

**Comment by PeterZhang17** [comment]
Thank you for you guide and I will do so

**Comment by PeterZhang17** [comment]
Please check the update ^^
